# Generated by Django 2.0.2 on 2020-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default='de6d624ad82547b58ad575f1aa50f164'),
        ),
    ]
