# Generated by Django 2.0.2 on 2020-01-04 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('customizations', models.CharField(max_length=300)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('menu_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuOptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
